export default [
  {
    id: "0",
    name: "Margherita",
    description:
      "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price:500,
    image:
      "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/margherita.90f9451fd66871fb6f9cf7d506053f18.1.jpg?width=251",
    veg: true,
  },
  {
    id: "1",
    name: "Tandoori Paneer",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 250,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/tandoori-paneer.4ef45717e972cf45b43c010e3cde5a22.1.jpg?width=251",
    veg: true,
  },
  {
    id: "2",
    name: "Veggie Supreme",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 562,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veggie-supreme-cheese-maxx.155c8cb465ac8782016af4d1d8d48c9b.1.jpg?width=251 ",
    veg: true,
  },
  {
    id: "3",
    name: "Double Paneer Supreme",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 678,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veggie-supreme.bc8dd369182b636ff171077efa53c344.1.jpg?width=251",
    veg: true,
  },
  {
    id: "4",
    name: "Veg Kabab Suprise",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 456,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veg-kebab-surprise.abab1dff179ab8cf95a59f30d6352297.1.jpg?width=251",
    veg: true,
  },
  {
    id: "5",
    name: "Schezwan Margherita",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 892,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/schezwan-margherita.4371d9483546db47a97c5503ccad0c2f.1.jpg?width=251",
    veg: true,
  },
  {
    id: "6",
    name: "Veg Kebab Suprise",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 342,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veg-kebab-surprise.abab1dff179ab8cf95a59f30d6352297.1.jpg?width=251",
    veg: true,
  },
  {
    id: "7",
    name: "Veggie Supreme",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 672,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veggie-supreme.bc8dd369182b636ff171077efa53c344.1.jpg?width=251",
    veg: true,
  },
  {
    id: "8",
    name: "Only Cheesy",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 892,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/only-cheesy-pan-personal.951dbe6ee07dafc48e04fe9a1bbe4ddb.1.jpg?width=251",
    veg: true,
  },
  {
    id: "9",
    name: "Italian Onion Tomato",
    description: "Pizza topped with our herb-infused signature pan sauce and 100% mozzarella cheese. A classic treat for all cheese lovers out there!",
    price: 892,
    image: "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/italian-onion-tomato-pan-personal.cb37b0766ef3ba8844fa69b2d073c215.1.jpg?width=251",
    veg: true,
  },
];
